### ISSUE TITLE
The Edge Function "api/og" size is 1.02 MB and your plan size limit is 1 MB

### ISSUE THREAD

**Issue by ShreyaPandyaa** [vercel/commerce#1028]
Vercel deploy/build failed and throw the following error.

Error: The Edge Function "api/og" size is 1.02 MB and your plan size limit is 1 MB. Learn More: https://vercel.link/edge-function-size

![Build_error](https://github.com/vercel/commerce/assets/127757360/95c9b3e6-77e9-4fb9-8467-4bc8abfde9ed)

**Comment by itsanishjain** [comment]
It is what it is, either you can remove edge runtime or just upgrade to pro plan

**Comment by leerob** [comment]
Are you seeing this on the default template with no changes?

**Comment by itsanishjain** [comment]
Yes Lee.

**Comment by ShreyaPandyaa** [comment]
> Are you seeing this on the default template with no changes?

Yes @leerob

**Comment by masapasa** [comment]
@leerob same here. is there a fix?

**Comment by ZeroPie** [comment]
The fonts have the following file sizes.

Inter-Bold.ttf : 316 kb
Inter-Regular.ttf: 310 kb

In my case i just removed the bold font.

But reducing the font file sizes would also be a fix.
https://rovity.io/reduce-web-font-size/

**Comment by ShreyaPandyaa** [comment]
I got this error on setting up the vercel/commerce setup with vercel. Can you draw attention to it..
![error-image](https://github.com/vercel/commerce/assets/127757360/9e9b854c-aace-4319-aa74-04f8798f36f7)

**Comment by star-ot** [comment]
> I got this error on setting up the vercel/commerce setup with vercel. Can you draw attention to it.. ![error-image](https://user-images.githubusercontent.com/127757360/241884118-9e9b854c-aace-4319-aa74-04f8798f36f7.png)

#1010

**Comment by manovotny** [comment]
This should be fixed now with #1043 because an unnecessary font was removed. Please let me know if that is not the case.

**Comment by tenosh** [comment]
![image](https://github.com/vercel/commerce/assets/32285955/5f4c0da6-d437-45f4-acd0-82820b5e0cdd)
Seems the issue still persists with open graph image convention

**Comment by zajcomm** [comment]
I had the same issue even after upgrading to pro. 
I am trying to clone a vercel template, and wonder if I should delete and try again as now on pro.

**Comment by leerob** [comment]
Please try the latest version on `main` 🙏

**Comment by zajcomm** [comment]
It was my mistake.. I think, I assumed once I upgrade it will automatically resolve the issue, but I had to rather move the project to the pro team.

**Comment by manovotny** [comment]
I just tested deploying the Commerce template in its current state (what's currently in `main`) to a Vercel Hobby account and it worked just fine. A Pro account is not required.

**Comment by kissu** [comment]
I don't have a lot of NextJS experience but I tried various things based on the commits that I saw on the `main` branch, they were all not successful. I was also looking for something quite simple to ship to try things out by using the [Saleor variant](https://github.com/saleor/nextjs-commerce), the idea was to host it on Vercel since it is meant for it.

Getting a bit frustrated not fully understanding and with no time to make an in-depth diff between the 2 projects, I just commented out the whole endpoint as [shown here](https://github.com/kissu/nextjs-commerce/commit/122048d9d6005908e96d562563e2b4839ca07f67).

Not a big deal for my use-case anyway, if that helps any people. 🤗

**Comment by JackHowa** [comment]
Also seeing this on the chat ai repo https://github.com/JackHowa/agile-ai

**Comment by kissu** [comment]
@JackHowa just try my solution. 👆🏻

**Comment by JackHowa** [comment]
Thanks @kissu! Had to rip out a different edge function that was over for the ai chat repo https://github.com/JackHowa/agile-ai/commit/f37d3233ad032c0cf3517613e069214678ed8c2d "share" and the ui as well

**Comment by jonsherrard** [comment]
Some added info for googlers: A previously working og-image endpoint with a font being loaded started failing after updating to `0.5.19`. Rolling back to `0.5.18` worked.

**Comment by Dajust** [comment]
I can confirm that downgrading to `0.5.18` fixes the problem. Thanks @jonsherrard.
