### ISSUE TITLE
Deploying new instance of Nextjs Commerce in Vercel fails with 404

### ISSUE THREAD

**Issue by robearlam** [vercel/commerce#672]
Hi,

I've attempted several times to deploy a new instance of Nextjs Commerce through the Vercel portal, but it fails. The build output looks to be very truncated compared with previous successful deployments I've done in the past.

```
07:56:37.771 | Cloning completed: 798.906ms
07:56:38.035 | Analyzing source code...
07:56:39.501 | Uploading build outputs...
07:56:45.681 | Deploying build outputs...
07:56:55.524 | Done with "."
```

When accessing the deployed site, I am presented with a 404 error:
![image](https://user-images.githubusercontent.com/2149251/152870964-f8549a48-7677-46d4-ae00-358d893f8eae.png)

You can see the erroring instance I'm trying to access here: https://commerce-fhgww6ugq-robearlam.vercel.app/
The repo used to deploy from is: https://github.com/robearlam/commerce (This is the default cloned code, without any changes)

Thanks!

**Comment by juancamiloqhz** [comment]
I'm having the same issue 
Change the build comman to 
cd ../ && npx turbo run build --scope=site --include-dependencies --no-deps
And also change project folder to "site"
Then manually trigger a redeploy to build the app, but still 404 after build is complete

**Comment by neneji** [comment]
what i did is:
in `Build & Development Settings`
1. set the `FRAMEWORK PRESET` to `Next.js`
2. set the `BUILD COMMAND` to `turbo run build`
2. set the `OUTPUT DIRECTORY` to `site/.next`

i dont know if there is a better way to config it or not, cannot find any guide about that...

**Comment by dominiksipowicz** [comment]
Hi @robearlam @juancamiloqhz 
Please try using the link https://vercel.com/new and selecting "Next.js Commerce". It should automatically clone the repository to your GitHub account, choose the integration (or skip provider) and deploy to Vercel automatically with the correct settings.

**Comment by robearlam** [comment]
This was related to the change over to monorepo, looks to have been solved now.

**Comment by guibovo** [comment]
I've forked the repo - worked a bit on it and deployed on Vercel, I'm still facing this issue.

https://vercel.com/guibovo/commerce/Dmdu8ExwiZxwqzcUK2WyroQiA2xL

<img width="961" alt="image" src="https://user-images.githubusercontent.com/3513557/183699996-ee651a4f-8bfb-4714-b38f-adc424af0a35.png">



When creating a from https://vercel.com/new it works fine, but when I change the env vars to point to Shopify, and try to redeploy, it breaks the build, And removing them, makes it work again

<img width="1258" alt="image" src="https://user-images.githubusercontent.com/3513557/183700255-9831df5b-d62a-4f4c-82bb-a0459949d836.png">
